

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./WEB:/usr/share/nginx/html/
      - ./certs:/etc/nginx/certs/
      - ./nginx.conf:/etc/nginx/nginx.conf

    
